export type Agent = {
  id: string;
  name: string;
  type: string;
  avatar?: string;
  status: 'working' | 'idle' | 'offline';
  currentTask?: string;
  tasksExecuted?: number;
  tasksCompleted: number;
  tasksFailed?: number;
  completionRate?: number;
  uptime: string;
  systemPrompt?: string;
  skills?: string[];
  model?: string;
  provider?: string;
  temperature?: number;
  maxTokens?: number;
  topP?: number;
  departmentId?: string;
  accessLevel?: 'private' | 'team' | 'public';
  allowedKnowledge?: string[];
  allowedMemory?: string[];
  topK?: number;
  similarityThreshold?: number;
};
