"""Initial schema - create all tables

Revision ID: 066e30212dbb
Revises:
Create Date: 2026-01-20 15:37:47.946756

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "066e30212dbb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_templates",
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("default_skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("default_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("template_id"),
    )
    op.create_index(op.f("ix_agent_templates_name"), "agent_templates", ["name"], unique=True)
    op.create_table(
        "skills",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("interface_definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("dependencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("skill_id"),
    )
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "agents",
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("agent_type", sa.String(length=100), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("container_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("agent_id"),
    )
    op.create_index("idx_agent_owner_status", "agents", ["owner_user_id", "status"], unique=False)
    op.create_index("idx_agent_type_status", "agents", ["agent_type", "status"], unique=False)
    op.create_index(op.f("ix_agents_agent_type"), "agents", ["agent_type"], unique=False)
    op.create_index(op.f("ix_agents_name"), "agents", ["name"], unique=False)
    op.create_index(op.f("ix_agents_owner_user_id"), "agents", ["owner_user_id"], unique=False)
    op.create_index(op.f("ix_agents_status"), "agents", ["status"], unique=False)
    op.create_table(
        "knowledge_items",
        sa.Column("knowledge_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("file_reference", sa.String(length=500), nullable=True),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column("item_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("knowledge_id"),
    )
    op.create_index(
        "idx_knowledge_owner_access",
        "knowledge_items",
        ["owner_user_id", "access_level"],
        unique=False,
    )
    op.create_index(
        "idx_knowledge_type_access",
        "knowledge_items",
        ["content_type", "access_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_items_access_level"), "knowledge_items", ["access_level"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_content_type"), "knowledge_items", ["content_type"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_items_owner_user_id"), "knowledge_items", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_knowledge_items_title"), "knowledge_items", ["title"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("access_level", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("permission_id"),
    )
    op.create_index(
        "idx_permission_user_resource",
        "permissions",
        ["user_id", "resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permissions_resource_id"), "permissions", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_permissions_resource_type"), "permissions", ["resource_type"], unique=False
    )
    op.create_index(op.f("ix_permissions_user_id"), "permissions", ["user_id"], unique=False)
    op.create_table(
        "resource_quotas",
        sa.Column("quota_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("max_agents", sa.Integer(), nullable=False),
        sa.Column("max_storage_gb", sa.Integer(), nullable=False),
        sa.Column("max_cpu_cores", sa.Integer(), nullable=False),
        sa.Column("max_memory_gb", sa.Integer(), nullable=False),
        sa.Column("current_agents", sa.Integer(), nullable=False),
        sa.Column("current_storage_gb", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("quota_id"),
    )
    op.create_index(op.f("ix_resource_quotas_user_id"), "resource_quotas", ["user_id"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("log_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("resource_type", sa.String(length=100), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.agent_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("log_id"),
    )
    op.create_index(
        "idx_audit_action_timestamp", "audit_logs", ["action", "timestamp"], unique=False
    )
    op.create_index(
        "idx_audit_resource", "audit_logs", ["resource_type", "resource_id"], unique=False
    )
    op.create_index(
        "idx_audit_user_timestamp", "audit_logs", ["user_id", "timestamp"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(op.f("ix_audit_logs_agent_id"), "audit_logs", ["agent_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("goal_text", sa.Text(), nullable=False),
        sa.Column("parent_task_id", sa.UUID(), nullable=True),
        sa.Column("assigned_agent_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("dependencies", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assigned_agent_id"], ["agents.agent_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_task_id"], ["tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index("idx_task_agent_status", "tasks", ["assigned_agent_id", "status"], unique=False)
    op.create_index("idx_task_created_at", "tasks", ["created_at"], unique=False)
    op.create_index("idx_task_parent", "tasks", ["parent_task_id"], unique=False)
    op.create_index("idx_task_user_status", "tasks", ["created_by_user_id", "status"], unique=False)
    op.create_index(
        op.f("ix_tasks_assigned_agent_id"), "tasks", ["assigned_agent_id"], unique=False
    )
    op.create_index(
        op.f("ix_tasks_created_by_user_id"), "tasks", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_parent_task_id"), "tasks", ["parent_task_id"], unique=False)
    op.create_index(op.f("ix_tasks_priority"), "tasks", ["priority"], unique=False)
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.execute(sa.text("DROP TABLE IF EXISTS schema_version"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schema_version",
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "applied_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("version", name=op.f("schema_version_pkey")),
    )
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_priority"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_parent_task_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_created_by_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_assigned_agent_id"), table_name="tasks")
    op.drop_index("idx_task_user_status", table_name="tasks")
    op.drop_index("idx_task_parent", table_name="tasks")
    op.drop_index("idx_task_created_at", table_name="tasks")
    op.drop_index("idx_task_agent_status", table_name="tasks")
    op.drop_table("tasks")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_agent_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index("idx_audit_user_timestamp", table_name="audit_logs")
    op.drop_index("idx_audit_resource", table_name="audit_logs")
    op.drop_index("idx_audit_action_timestamp", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_resource_quotas_user_id"), table_name="resource_quotas")
    op.drop_table("resource_quotas")
    op.drop_index(op.f("ix_permissions_user_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_resource_type"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_resource_id"), table_name="permissions")
    op.drop_index("idx_permission_user_resource", table_name="permissions")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_knowledge_items_title"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_owner_user_id"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_content_type"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_access_level"), table_name="knowledge_items")
    op.drop_index("idx_knowledge_type_access", table_name="knowledge_items")
    op.drop_index("idx_knowledge_owner_access", table_name="knowledge_items")
    op.drop_table("knowledge_items")
    op.drop_index(op.f("ix_agents_status"), table_name="agents")
    op.drop_index(op.f("ix_agents_owner_user_id"), table_name="agents")
    op.drop_index(op.f("ix_agents_name"), table_name="agents")
    op.drop_index(op.f("ix_agents_agent_type"), table_name="agents")
    op.drop_index("idx_agent_type_status", table_name="agents")
    op.drop_index("idx_agent_owner_status", table_name="agents")
    op.drop_table("agents")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_agent_templates_name"), table_name="agent_templates")
    op.drop_table("agent_templates")
    # ### end Alembic commands ###
