"""add_llm_provider_test_status

Revision ID: 57fe33834201
Revises: 5f09c5144d20
Create Date: 2026-01-23 17:06:08.677970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57fe33834201'
down_revision: Union[str, Sequence[str], None] = '5f09c5144d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('last_test_status', sa.String(length=20), nullable=True))
    op.add_column('llm_providers', sa.Column('last_test_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('llm_providers', sa.Column('last_test_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'last_test_error')
    op.drop_column('llm_providers', 'last_test_time')
    op.drop_column('llm_providers', 'last_test_status')
    # ### end Alembic commands ###
