"""Shared sandbox runtime environment helpers.

These helpers define the authoritative Python/pip runtime contract used by
session sandbox bash commands and code execution.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Dict, Mapping, Optional

from virtualization.container_manager import get_container_manager

DEFAULT_INTERNAL_PIP_CACHE_DIR = "/opt/linx_pip_cache"
DEFAULT_INTERNAL_PYTHON_DEPS_DIR = "/opt/linx_python_deps"
DEFAULT_INTERNAL_DEP_WORKDIR = "/opt/linx_runtime"
DEFAULT_INTERNAL_RUNTIME_ENV_PATH = f"{DEFAULT_INTERNAL_DEP_WORKDIR}/env.sh"

_PASSTHROUGH_PIP_ENV_KEYS = (
    "PIP_INDEX_URL",
    "PIP_EXTRA_INDEX_URL",
    "PIP_TRUSTED_HOST",
    "PIP_CERT",
    "PIP_CLIENT_CERT",
)


def _stringify_env(raw_env: Optional[Mapping[str, object]]) -> Dict[str, str]:
    env: Dict[str, str] = {}
    if not isinstance(raw_env, Mapping):
        return env

    for key, value in raw_env.items():
        env_key = str(key or "").strip()
        if not env_key or value is None:
            continue
        env[env_key] = str(value)
    return env


def build_sandbox_runtime_env(raw_env: Optional[Mapping[str, object]] = None) -> Dict[str, str]:
    """Build authoritative environment variables for sandbox Python runtime."""
    env = _stringify_env(raw_env)

    dep_target = DEFAULT_INTERNAL_PYTHON_DEPS_DIR
    env["PIP_CACHE_DIR"] = DEFAULT_INTERNAL_PIP_CACHE_DIR
    env["LINX_DEP_WORKDIR"] = DEFAULT_INTERNAL_DEP_WORKDIR
    env["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
    env["PIP_DEFAULT_TIMEOUT"] = "120"
    env["PIP_RETRIES"] = "6"
    env["PIP_TARGET"] = dep_target
    env["PYTHONNOUSERSITE"] = "1"
    env["PIP_USER"] = "0"

    existing_pythonpath = str(env.get("PYTHONPATH", "")).strip()
    if existing_pythonpath:
        path_entries = [entry for entry in existing_pythonpath.split(":") if entry]
        env["PYTHONPATH"] = (
            existing_pythonpath if dep_target in path_entries else f"{dep_target}:{existing_pythonpath}"
        )
    else:
        env["PYTHONPATH"] = dep_target

    for env_key in _PASSTHROUGH_PIP_ENV_KEYS:
        env_value = os.getenv(env_key)
        if env_value:
            env[env_key] = env_value

    return env


def build_python_runtime_summary(raw_env: Optional[Mapping[str, object]] = None) -> Dict[str, object]:
    """Build compact Python runtime summary for runtime_capabilities."""
    env = build_sandbox_runtime_env(raw_env)
    return {
        "executable": "python3",
        "pip_target": env["PIP_TARGET"],
        "pythonpath": env["PYTHONPATH"],
        "python_nousersite": env.get("PYTHONNOUSERSITE") == "1",
    }


def render_sandbox_runtime_env_script(raw_env: Optional[Mapping[str, object]] = None) -> str:
    """Render shell exports for the authoritative sandbox runtime environment."""
    env = build_sandbox_runtime_env(raw_env)
    ordered_keys = [
        "PIP_CACHE_DIR",
        "LINX_DEP_WORKDIR",
        "PIP_DISABLE_PIP_VERSION_CHECK",
        "PIP_DEFAULT_TIMEOUT",
        "PIP_RETRIES",
        "PIP_TARGET",
        "PYTHONPATH",
        "PYTHONNOUSERSITE",
        "PIP_USER",
    ]
    ordered_keys.extend(key for key in _PASSTHROUGH_PIP_ENV_KEYS if key in env)

    lines = ["#!/bin/sh", "# Generated by LinX sandbox runtime helpers"]
    for key in ordered_keys:
        value = env.get(key)
        if value is None:
            continue
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'export {key}="{escaped}"')
    return "\n".join(lines) + "\n"


def write_sandbox_runtime_env_file(
    container_id: str,
    path: str = DEFAULT_INTERNAL_RUNTIME_ENV_PATH,
    *,
    container_manager=None,
    raw_env: Optional[Mapping[str, object]] = None,
) -> None:
    """Write authoritative runtime env exports into the sandbox container."""
    manager = container_manager or get_container_manager()
    parent_dir = str(Path(path).parent)
    manager.exec_in_container(
        container_id=container_id,
        command=f"mkdir -p {parent_dir}",
    )
    manager.write_file_to_container(
        container_id=container_id,
        file_path=path,
        content=render_sandbox_runtime_env_script(raw_env),
        mode=0o644,
    )
