"""Database module for Digital Workforce Platform."""

from .connection import (
    DatabaseConnectionPool,
    close_connection_pool,
    get_connection_pool,
    get_db_session,
)
from .migrations import (
    MigrationRunner,
    get_migration_runner,
    run_migrations_on_startup,
)
from .models import (
    ABACPolicyModel,
    Agent,
    AgentConversationMemoryState,
    AgentSchedule,
    AgentScheduleRun,
    AgentSkillBinding,
    AuditLog,
    Base,
    KnowledgeItem,
    Permission,
    ResourceQuota,
    SessionLedger,
    SessionLedgerEvent,
    Skill,
    SkillCandidate,
    SkillRevision,
    Task,
    User,
    UserMemoryEntry,
    UserMemoryLink,
    UserMemoryView,
)
from .project_execution_models import (
    AgentProvisioningProfile,
    ExecutionNode,
    ExternalAgentBinding,
    ExternalAgentDispatch,
    ExternalAgentDispatchEvent,
    ExternalAgentInstallToken,
    ExternalAgentProfile,
    Project,
    ProjectAgentBinding,
    ProjectAuditEvent,
    ProjectExtensionPackage,
    ProjectPlan,
    ProjectRun,
    ProjectSkillPackage,
    ProjectSpace,
    ProjectTask,
)

__all__ = [
    # Models
    "Base",
    "User",
    "Agent",
    "AgentConversationMemoryState",
    "Task",
    "Skill",
    "Permission",
    "AgentSkillBinding",
    "AgentSchedule",
    "AgentScheduleRun",
    "SessionLedger",
    "SessionLedgerEvent",
    "UserMemoryEntry",
    "UserMemoryLink",
    "UserMemoryView",
    "SkillCandidate",
    "SkillRevision",
    "KnowledgeItem",
    "ResourceQuota",
    "AuditLog",
    "ABACPolicyModel",
    "Project",
    "ProjectAgentBinding",
    "AgentProvisioningProfile",
    "ExecutionNode",
    "ExternalAgentBinding",
    "ExternalAgentDispatch",
    "ExternalAgentDispatchEvent",
    "ExternalAgentInstallToken",
    "ExternalAgentProfile",
    "ProjectTask",
    "ProjectPlan",
    "ProjectRun",
    "ProjectSpace",
    "ProjectSkillPackage",
    "ProjectExtensionPackage",
    "ProjectAuditEvent",
    # Connection Pool
    "DatabaseConnectionPool",
    "get_connection_pool",
    "close_connection_pool",
    "get_db_session",
    # Migrations
    "MigrationRunner",
    "get_migration_runner",
    "run_migrations_on_startup",
]
