"""Access Control System for Digital Workforce Platform.

This module implements authentication and authorization using RBAC and ABAC models.

References:
- Requirements 14: User-Based Access Control
- Design Section 8: Access Control System
"""

from access_control.abac import (
    ABACEvaluationEngine,
    ABACPolicy,
    Condition,
    ConditionGroup,
    ConditionOperator,
    LogicalOperator,
    PolicyEffect,
    create_business_hours_policy,
    create_clearance_level_policy,
    create_department_access_policy,
    evaluate_abac_access,
    get_abac_engine,
)
from access_control.agent_ownership import (
    can_control_agent,
    can_create_agent,
    can_delete_agent,
    can_update_agent,
    get_agent_owner_id,
    get_user_agents,
    require_agent_ownership,
    verify_agent_ownership,
)
from access_control.audit_logger import (
    AuditEventType,
    get_audit_logs,
    log_abac_policy_evaluation,
    log_access_control_event,
    log_agent_access,
    log_authentication_event,
    log_knowledge_access,
    log_memory_access,
    log_permission_check,
    log_resource_access,
    log_user_management_event,
)
from access_control.jwt_auth import (
    JWTAuthenticationError,
    JWTTokenExpiredError,
    JWTTokenInvalidError,
    TokenData,
    TokenPair,
    blacklist_session_id,
    blacklist_token,
    blacklist_token_jti,
    clear_blacklist,
    create_access_token,
    create_refresh_token,
    create_token_pair,
    decode_token,
    get_token_expiration,
    get_token_remaining_time,
    is_token_blacklisted,
    refresh_access_token,
    verify_token,
)
from access_control.knowledge_filter import (
    KnowledgeAccessLevel,
    build_milvus_filter_expr,
    can_access_knowledge_item,
    check_knowledge_delete_permission,
    check_knowledge_write_permission,
    filter_knowledge_query,
    filter_knowledge_results,
    get_accessible_knowledge_ids,
)
from access_control.memory_filter import (
    can_access_skill_learning,
    check_skill_learning_delete_permission,
    check_skill_learning_write_permission,
)
from access_control.models import UserModel, hash_password, verify_password
from access_control.permissions import (
    CurrentUser,
    PermissionDeniedError,
    check_resource_ownership,
    check_user_permission,
    filter_by_permission,
    get_current_user,
    get_permission_scope,
    log_permission_denial,
    require_permission,
    require_role,
    verify_resource_access,
)
from access_control.policy_loader import (
    PolicyLoader,
    PolicyNotFoundError,
    PolicySerializationError,
    get_policy_loader,
    load_policies_on_startup,
)
from access_control.rbac import (
    ROLE_DEFINITIONS,
    Action,
    Permission,
    ResourceType,
    Role,
    RoleDefinition,
    check_permission,
    get_all_roles,
    get_role_definition,
    get_role_hierarchy,
    get_role_permissions,
    get_role_summary,
    is_role_higher_or_equal,
    validate_role,
)
from access_control.registration import (
    DuplicateUserError,
    RegistrationError,
    RegistrationRequest,
    RegistrationResponse,
)
from access_control.registration import ValidationError as RegistrationValidationError
from access_control.registration import (
    register_user,
    register_user_admin,
    register_user_self,
)

__all__ = [
    # User models
    "UserModel",
    "hash_password",
    "verify_password",
    # JWT authentication
    "TokenData",
    "TokenPair",
    "JWTAuthenticationError",
    "JWTTokenExpiredError",
    "JWTTokenInvalidError",
    "create_access_token",
    "create_refresh_token",
    "create_token_pair",
    "decode_token",
    "verify_token",
    "refresh_access_token",
    "blacklist_token",
    "blacklist_token_jti",
    "blacklist_session_id",
    "is_token_blacklisted",
    "clear_blacklist",
    "get_token_expiration",
    "get_token_remaining_time",
    # RBAC
    "Role",
    "ResourceType",
    "Action",
    "Permission",
    "RoleDefinition",
    "get_role_definition",
    "validate_role",
    "get_all_roles",
    "get_role_hierarchy",
    "is_role_higher_or_equal",
    "check_permission",
    "get_role_permissions",
    "get_role_summary",
    "ROLE_DEFINITIONS",
    # Permission checking
    "CurrentUser",
    "PermissionDeniedError",
    "get_current_user",
    "require_permission",
    "require_role",
    "check_resource_ownership",
    "check_user_permission",
    "log_permission_denial",
    "filter_by_permission",
    "get_permission_scope",
    "verify_resource_access",
    # ABAC
    "Condition",
    "ConditionGroup",
    "ConditionOperator",
    "LogicalOperator",
    "PolicyEffect",
    "ABACPolicy",
    "ABACEvaluationEngine",
    "get_abac_engine",
    "evaluate_abac_access",
    "create_department_access_policy",
    "create_clearance_level_policy",
    "create_business_hours_policy",
    # Policy Loader
    "PolicyLoader",
    "PolicySerializationError",
    "PolicyNotFoundError",
    "get_policy_loader",
    "load_policies_on_startup",
    # User Registration
    "register_user",
    "register_user_self",
    "register_user_admin",
    "RegistrationRequest",
    "RegistrationResponse",
    "RegistrationValidationError",
    "DuplicateUserError",
    "RegistrationError",
    # Knowledge Base Filtering
    "KnowledgeAccessLevel",
    "can_access_knowledge_item",
    "filter_knowledge_query",
    "build_milvus_filter_expr",
    "filter_knowledge_results",
    "get_accessible_knowledge_ids",
    "check_knowledge_write_permission",
    "check_knowledge_delete_permission",
    # Skill-learning access control
    "can_access_skill_learning",
    "check_skill_learning_write_permission",
    "check_skill_learning_delete_permission",
    # Agent Ownership Validation
    "verify_agent_ownership",
    "require_agent_ownership",
    "get_user_agents",
    "can_create_agent",
    "can_update_agent",
    "can_delete_agent",
    "can_control_agent",
    "get_agent_owner_id",
    # Audit Logging
    "AuditEventType",
    "log_access_control_event",
    "log_authentication_event",
    "log_permission_check",
    "log_resource_access",
    "log_agent_access",
    "log_knowledge_access",
    "log_memory_access",
    "log_abac_policy_evaluation",
    "log_user_management_event",
    "get_audit_logs",
]
